# Generated by Django 4.2.15 on 2025-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-id'], 'verbose_name_plural': '05.Products Colors'},
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Sizes', 'Sizes'), ('Colors', 'Colors'), ('Sizes-Colors', 'Sizes-Colors')], default='NONE', max_length=12),
        ),
    ]
