# Generated by Django 4.2.15 on 2025-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
